telemetry:
  username: ''
  password: ''
  api_url: "http://localhost:5000"
krkn_ai:
  dataset_path: /tmp
  threads: 15
  reuse_dataset: True
  dataset_starting_timestamp:   1711449184 # 0 if want to start to the very beginning
  scenarios:
    - class_name: ExitCodeScenario
      retrain: True
      package: krkn_ai.scenarios
      vector_db_path: /tmp/exit_code_scenario_2
      model:
        class_name: KrknOllama
        package: krkn_ai.llm
        endpoint: http://192.168.0.105:11434
        name: llama2-uncensored

