telemetry:
  username: ''
  password: ''
  api_url: "http://localhost:5000"
krkn_ai:
  llm_endpoint: ""
  chroma_db_path: ./chroma_db
  dataset_path: /tmp
  threads: 15
  llms:

  scenarios:
    - class_name: ExitCodeScenario
      package: krkn_ai.scenarios
      vector_db_path: /tmp/exit_code_scenario
      model:
        class_name: KrknOllama
        package: krkn_ai.llm
        endpoint: http://192.168.0.105:11434
        name: llama2-uncensored

